### PR TITLE
Add fuadbagus to Contributors list

### PR DESCRIPTION
**Pull request by fuadbagus**
## Description

Add fuadbagus to contributors list

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [x] I have added or run the performance tests that depict optimal execution times
- [x] New and existing unit tests pass locally and in the build (below) with my changes

## Acknowledgements

- [x] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [x] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by DaveSkender** [comment]
@fuadbagus thank you for your interest in contributing to the Stock.Indicators for .NET code repository.
Please refer to our [contributing guidelines](https://daveskender.github.io/Stock.Indicators/contributing/#content) for more information.  If you have specific contribution interests, please do let me know.

Our current work backlog is available here: [the Backlog](https://github.com/DaveSkender/Stock.Indicators/projects/1)

**Comment by fuadbagus** [comment]
@DaveSkender Thanks. I will look at the backlog items. It's my first time trying to participate on github and I though I need to be added as a contributor first before I can contribute.

**Comment by DaveSkender** [comment]
Nope need to be added.  As a side note, everything you did to setup you fork, your feature branch, and this PR was the right process.  Good job!

**Comment by fuadbagus** [comment]
@DaveSkender Unit testing is one of my interests.

**Comment by fuadbagus** [comment]
@DaveSkender Thank you for the feedback. I was wondering if I missed something in the process.

**Comment by DaveSkender** [comment]
If you're interested in unit testing, review my active PR #553.  I'm starting to do some improvements and could use some help upgrading older tests.

**Comment by fuadbagus** [comment]
@DaveSkender Thanks, will have a look.

**Pull request closed without merging**
