### PR TITLE
Williams Alligator

### PR DESCRIPTION
**Pull request by tanjera**
## Description

Implemented Williams Alligator, using formula from https://www.investopedia.com/articles/trading/072115/exploring-williams-alligator-indicator.asp

Fixes #(343)

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation, including INDICATORS.md, README.md, info.xml, etc
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [x] I have added or run the performance tests that depict execution times similar to others
- [x] New and existing unit tests pass locally with my changes

## Acknowledgements

- [x] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [x] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by tanjera** [comment]
Performance test:

// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1379 (1909/November2018Update/19H2)
AMD Ryzen 7 2700X, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.103
  [Host]     : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  DefaultJob : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT


|            Method |        Mean |     Error |    StdDev |
|------------------ |------------:|----------:|----------:|
|            GetAdl |   131.05 us |  2.497 us |  2.336 us |
|     GetAdlWithSma |   363.98 us |  6.419 us |  6.005 us |
|            GetAdx |   692.35 us |  4.290 us |  3.803 us |
|      GetAlligator |   265.02 us |  5.244 us |  5.386 us |
|           GetAlma |   218.87 us |  2.682 us |  2.377 us |
|          GetAroon |   367.89 us |  3.915 us |  3.470 us |
|            GetAtr |   155.17 us |  0.759 us |  0.672 us |
|        GetAwesome |   322.12 us |  1.728 us |  1.443 us |
|           GetBeta | 1,004.05 us |  4.040 us |  3.155 us |
| GetBollingerBands |   445.91 us |  1.892 us |  1.677 us |
|            GetBop |   267.76 us |  2.727 us |  2.551 us |
|            GetCci |   749.91 us |  3.805 us |  3.559 us |
|     GetChaikinOsc |   248.90 us |  3.182 us |  2.977 us |
|     GetChandelier |   362.91 us |  2.206 us |  2.063 us |
|           GetChop |   294.61 us |  2.048 us |  1.915 us |
|            GetCmf |   636.57 us |  8.837 us |  8.266 us |
|     GetConnorsRsi | 1,172.59 us | 11.785 us |  9.841 us |
|    GetCorrelation |   954.66 us | 16.814 us | 15.728 us |
|       GetDonchian |   348.20 us |  2.479 us |  2.319 us |
|      GetDoubleEma |   173.74 us |  1.788 us |  1.673 us |
|       GetElderRay |   156.02 us |  1.771 us |  1.570 us |
|            GetEma |    92.60 us |  0.774 us |  0.686 us |
|           GetEpma | 1,340.81 us |  5.616 us |  4.689 us |
|            GetFcb |   416.21 us |  3.397 us |  3.011 us |
|     GetForceIndex |   122.46 us |  0.713 us |  0.667 us |
|        GetFractal |   108.62 us |  0.677 us |  0.634 us |
|     GetHeikinAshi |   176.77 us |  1.604 us |  1.500 us |
|            GetHma | 1,188.32 us |  6.746 us |  5.633 us |
|    GetHtTrendline |   154.30 us |  2.113 us |  1.977 us |
|       GetIchimoku | 1,040.50 us |  9.174 us |  8.581 us |
|           GetKama |   307.23 us |  1.185 us |  1.051 us |
|        GetKeltner |   432.04 us |  3.039 us |  2.843 us |
|           GetMacd |   205.44 us |  2.283 us |  2.135 us |
|    GetMaEnvelopes |   141.31 us |  1.191 us |  1.114 us |
|           GetMama |   277.20 us |  2.530 us |  2.367 us |
|            GetMfi |   420.26 us |  2.024 us |  1.795 us |
|            GetObv |    56.88 us |  0.481 us |  0.450 us |
|     GetObvWithSma |   126.58 us |  2.507 us |  2.345 us |
|   GetParabolicSar |    93.56 us |  0.498 us |  0.441 us |
|    GetPivotPoints |    88.98 us |  0.899 us |  0.797 us |
|            GetPmo |   247.06 us |  1.573 us |  1.395 us |
|            GetPrs |   105.53 us |  0.636 us |  0.594 us |
|     GetPrsWithSma |   182.84 us |  1.514 us |  1.343 us |
|            GetPvo |   309.07 us |  3.042 us |  2.846 us |
|            GetRoc |    78.38 us |  1.537 us |  1.509 us |
|     GetRocWithSma |   336.37 us |  1.508 us |  1.337 us |
|            GetRsi |   306.00 us |  2.809 us |  2.627 us |
|          GetSlope |   944.52 us |  4.018 us |  3.356 us |
|            GetSma |    97.73 us |  0.673 us |  0.630 us |
|    GetSmaExtended |   892.87 us |  3.372 us |  2.989 us |
|           GetSmma |    92.21 us |  0.677 us |  0.633 us |
|     GetStarcBands |   401.39 us |  3.636 us |  3.401 us |
|         GetStdDev |   271.01 us |  1.746 us |  1.633 us |
|  GetStdDevWithSma |   351.42 us |  1.341 us |  1.120 us |
| GetStdDevChannels | 1,019.41 us |  4.355 us |  4.074 us |
|          GetStoch |   390.00 us |  4.178 us |  3.908 us |
|       GetStochRsi |   648.50 us |  3.844 us |  3.407 us |
|     GetSuperTrend |   296.38 us |  2.969 us |  2.777 us |
|      GetTripleEma |   253.07 us |  3.880 us |  3.029 us |
|           GetTrix |   302.75 us |  2.254 us |  1.998 us |
|    GetTrixWithSma |   359.51 us |  4.192 us |  3.501 us |
|            GetTsi |   345.69 us |  2.002 us |  1.774 us |
|             GetT3 |   438.63 us |  2.349 us |  2.083 us |
|     GetUlcerIndex | 1,439.81 us |  2.482 us |  2.073 us |
|       GetUltimate |   515.66 us |  1.973 us |  1.647 us |
|         GetVolSma |   102.01 us |  0.487 us |  0.406 us |
|         GetVortex |   264.19 us |  1.710 us |  1.516 us |
|           GetVwap |    92.25 us |  1.106 us |  1.034 us |
|      GetWilliamsR |   287.62 us |  1.247 us |  1.105 us |
|            GetWma |   633.05 us |  1.754 us |  1.640 us |
|         GetZigZag |   129.89 us |  1.534 us |  1.360 us |

**Comment by DaveSkender** [comment]
Awesome.  Thank for helping out on this one.  I see you've used an overload, which is nice.  I've been considering doing this on other indicators that have a strong set of defaults or alternative uses, but always get hung up on the complexity tradeoff.

Do the lookback periods need to be sized (and validated) relative to each other?

I'll probably take a look at this over the weekend.

**Comment by tanjera** [comment]
Yeah, I made the overload since the indicator is traditionally that one set
of parameters, but wanted to be able for people to tweak it as they like.
Overloads are my best friend sometimes.

The lookback periods actually are entirely independent of each other. They
are 3 different SMMAs of different smoothing periods- their only link to
each other is the visual patterns they show when charted.

And as it turns out, the SMMAs are calculated just like you had ended up
redoing the SMMA formula, with only 2 steps (initial SMA, then one formula
for SMMA) but the SMMA tosses in weighting for the smoothing period.

**Comment by DaveSkender** [comment]
I suspect we might need to enforce `lookbackJaw > lookbackLips > lookbackTeeth` or the concepts of the system may get messed up, or at least the results data will be mixed up.  Also, I'm wondering if Williams simply decremented by 3 (or a single amount from the lookback period) to get smoothing or if `smoothingLips<==lookbackJaw` for example, or if they are all truly independent.  I'm all for flexibility in using parameters; however, I just want to make sure we enforce proper ranges that do not intrinsically violate the rules and intent of the indicator.

**Comment by DaveSkender** [comment]
In looking at Bill William's description of Alligator in his book New Trading Dimensions, he describes the three lines as:

- Jaw (blue line) - 13-bar SMMA offset by 8 bars into the future
- Teeth (red line) - 8-bar SMMA offset by 5 bars into the future and is one significant timeframe lower
- Lips (green line) - 5-bar SMMA offset by 3 bars into the future and is one significant timeframe lower

He refers to these as Balance Lines as "that place where the current price would be if there was no new incoming
information".  I'm not exactly sure what that means but suspect there is a correlation between the SMMA lookback period and this offset period that makes sense.

**Comment by DaveSkender** [comment]
@tanjera let me know if you have time to work on this one; otherwise, I can take a shot at finishing it.  I'd like to get this one and then Gator Oscillator (#388) done, then release the package v1.10 with all 5 of the new unpublished indicators.

**Comment by tanjera** [comment]
> In looking at Bill William's description of Alligator in his book New Trading Dimensions, he describes the three lines as:
> 
> * Jaw (blue line) - 13-bar SMMA offset 8 bars into the future
> * Teeth (red line) - 8-bar SMMA offset 5 bars into the future and is one significant timeframe lower
> * Lips (green line) - 5-bar SMMA offset 3 bars into the future and is one significant timeframe lower
> 
> He refers to these as Balance Lines as "that place where the current price would be if there was no new incoming
> information". I'm not exactly sure what that means but suspect there is a correlation between the SMMA lookback period and this offset period that makes sense.
> 
> I think we should go with the original offset approach, instead of the alternative modified smoothing approach. I suspect some charting sites have tweaked the formula to use this alternate smoothing technique to make it easier to calculate.

I wasn't sure either, since I had been seeing different descriptions, whether the SMMA was smoothed out to project further to the right/future, or whether the data was actually shifted to the right/future. I'm wondering whether to just write both methods and visualize them on charts, comparing the two. Unfortunately, I don't actually use any C# charting software, since all of the programming I've done just directly modifies data- I've never set up any charting software or APIs to visualize this indicator on to see how the results are turning out.

As far as writing a method to shift the SMMA's to the right/future, I would probably go about this by initializing a stack of `AlligatorResult[history.Count]`. While running the SMMAs, instead of using the smoothing technique, I would just get the basic `GetSMMA(lookbackPeriod)` and insert it into `resultArray[index+shiftToFuture]` (of course, checking for 'out of bounds' exceptions). Sound about right to you? I just wanted to check before putting it together.

**Comment by DaveSkender** [comment]
GetSmma runs fast, so I’d try using it first, the roll through history to build the results.  I don’t think you’ll need an intermediate array to store values, just offset backwards to pick the SMMA value.

 Check the speed when done.  This approach will do 4 passes on history, will be slower than a single pass approach, but if it’s less than 500 us, it’s probably okay.

**Comment by tanjera** [comment]
Finally getting some time today to work on this! I'll keep you posted.

**Comment by tanjera** [comment]
Ready for you to look through the code. I changed the Alligator implementation as we discussed- they're now 3 SMMAs offset into the future rather than smoothed. The Excel spreadsheet was also redone with the implementation, and all the updated tests passed.

I removed the original additional overload and decided to set all of the `lookback` and `offset` periods as hard-coded variables (no incoming parameters besides `history`). That way, they can be easily modified to feed in as parameters if you want to take it that route. 

I only ran a perf test for `GetAlligator` and `GetSmma` for comparison. I did reuse code from GetSmma, but I didn't actually make any function calls to it from `GetAlligator` so they are still distinctly separate.

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1440 (1909/November2018Update/19H2)
AMD Ryzen 7 2700X, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  DefaultJob : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT


|       Method |      Mean |    Error |   StdDev |
|------------- |----------:|---------:|---------:|
| GetAlligator | 209.81 us | 0.884 us | 0.738 us |
|      GetSmma |  94.43 us | 0.996 us | 0.932 us |

// * Hints *
Outliers
  MarkIndicators.GetAlligator: Default -> 2 outliers were removed (213.86 us, 214.11 us)

**Comment by DaveSkender** [comment]
Oh, nice, that's quite fast.  Did you try the GetSmma approach at all or just go straight for the single pass approach?  Just curious to see what the difference in performance might have been.  Not important!  I'll take a closer look at this over the weekend.

Quick glance:

1. You might try `historyList.Select...` to initialize the results dataset.  Probably negligible perf difference, but can be cleaner code.
2. I'm okay with the static parameters.  If users complain we can revisit later.  Personally, for this one, I think it's dangerous to be messing with the parameters anyway.  It could easily produce maligned results if you don't really know what it's doing.  From Williams' docs, these numbers were sorta reverse engineered anyway.

**Comment by tanjera** [comment]
> Did you try the GetSmma approach at all or just go straight for the single pass approach? 

I just went straight for the single pass approach. It conceptually seemed easier for me to just copy/paste the GetSmma code but insert the values into the array at specific offsets (checking to ensure I didn't overrun the array index with an out-of-bounds exception)

> 1. You might try `historyList.Select...` to initialize the results dataset.  Probably negligible perf difference, but can be cleaner code.

I'm actually not sure how to initialize a dataset that way. I love `.Select()` but really only use it to recast datasets to simpler arrays. I didn't quite have the brain power to get creative today, but I'll try that sometime.

> 2. I'm okay with the static parameters.  If users complain we can revisit later.  Personally, for this one, I think it's dangerous to be messing with the parameters anyway.  It could easily produce maligned results if users don't really know what it's doing.  From Williams' docs, these numbers were sorta reverse engineered anyway.

Agreed, agreed, agreed. It would be a ton of error checking with an end result of potential misaligned results, indices overrun, etc. While my personal projects can be rife with bugs, it's probably best not to open that up to production code. And like you said, it sounds like he designed these parameters back-engineered based on visual chart analysis.

**Review by DaveSkender — APPROVED** [review]
Looks good.  I'll add Gator Oscillator, update all charts, docs, then release the batch this weekend.

**Pull request merged**
