### PR TITLE
add Choppiness Index

### LINKED ISSUE #349: Choppiness Index
add [Choppiness Index](https://www.forexfactory.com/attachment.php/2876703?attachmentid=2876703&d=1530393505)

### PR DESCRIPTION
**Pull request by tanjera**
Thanks for contributing.  

## Description

Implemented Choppiness Index (CHOP) based on article "Measuring market choppiness with chaos" by Gibbons Burke (Trading Techniques, Oct 1993).

Fixes #349 

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation, including INDICATORS.md, README.md, info.xml, etc
- [x] My changes generate no new warnings
- [x] I have added unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [x] I have added performance tests that depict execution times similar to others
- [x] New and existing unit tests pass locally with my changes

## Acknowledgements

- [x] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [x] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by tanjera** [comment]
I couldn't figure out how to run the performance test... I also forgot to include the performance test code in this commit.

On the code review, you'll see I essentially modeled the functions and structures off of the existing code (specifically for BollingerBands and RSI), obviously calculating CHOP instead, and also changed some of the unit test criteria to match the CHOP index. No smoothing technique, requires N+1 history, and N>1.

I implemented the Excel functions in the corresponding Excel spreadsheet in the indicators/Chop/ folder for verification.

Hope it works out well! Thank you!

**Comment by DaveSkender** [comment]
I’ll take a closer review in the next couple days when I have more time.  I’ll go ahead and add the perf test to your branch if you don’t get to it.  Is the most common abbreviation CHOP or CI?

**Comment by tanjera** [comment]
I Googled around for more general links and information to put in the docs
(didn't include any- wasn't sure what the gold standard is for this kinda
stuff)- half of them called it CHOP, the other half didn't use acronyms.

I think it'd be best if you add the perf test. I wrote one (copy/paste with
an edited function call) but I'm not sure how to git push to a remote
branch that already has a pull request on it. I don't have too much
experience collaborating with git (pull requests, merges).

I think the math itself was fairly straightforward. Keep an eye out for
Chop.cs: line 71 ... not sure if I should explicitly prevent a
divide-by-zero with "Math.Log(lookbackPeriod)" even though lookbackPeriod
can't be 1 (which is the only result that Log(1) == 0).

Oh, and I see on Test.Chop.cs: line 73 ... I forgot to change
WriteLine("RSI..." to "CHOP" lol.

**Comment by DaveSkender** [comment]
In Git there’s basically a remote copy (on GitHub) and a local copy (on your computer) of your feature branch.  If you `git pull` you’ll get any changes from the remote copy from other people.  If you `git push` any new changes on your local are added to the remote, which is what we see in the PR.

In other words, if you make a change locally, commit, then push, you’ll update the code in the PR.

**Comment by DaveSkender** [comment]
I think the acronym CHOP is fine, descriptive enough.  From my quick scan, the code looks almost flawless, excellent work.  I’ll do a full check this weekend.

**Comment by tanjera** [comment]
Added the performance test and ran it. Results are:

```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1379 (1909/November2018Update/19H2)
AMD Ryzen 7 2700X, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.103
  [Host]     : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  DefaultJob : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT


|            Method |        Mean |     Error |    StdDev |
|------------------ |------------:|----------:|----------:|
|            GetAdl |   134.35 us |  2.618 us |  2.910 us |
|     GetAdlWithSma |   345.96 us |  0.420 us |  0.328 us |
|            GetAdx |   680.35 us |  2.843 us |  2.374 us |
|           GetAlma |   215.93 us |  2.066 us |  1.932 us |
|          GetAroon |   376.45 us |  4.469 us |  4.180 us |
|            GetAtr |   157.06 us |  1.502 us |  1.405 us |
|        GetAwesome |   318.91 us |  0.726 us |  0.606 us |
|           GetBeta | 1,023.67 us | 18.593 us | 17.392 us |
| GetBollingerBands |   453.98 us |  5.575 us |  4.656 us |
|            GetBop |   287.92 us |  5.553 us |  8.480 us |
|            GetCci |   752.86 us |  4.058 us |  3.168 us |
|     GetChaikinOsc |   248.40 us |  3.415 us |  3.195 us |
|     GetChandelier |   366.32 us |  2.896 us |  2.567 us |
|           GetChop |   295.56 us |  3.438 us |  2.684 us |
|            GetCmf |   617.73 us |  7.480 us |  6.631 us |
|     GetConnorsRsi | 1,187.54 us |  6.008 us |  5.017 us |
|    GetCorrelation |   936.26 us | 10.653 us |  9.443 us |
|       GetDonchian |   354.59 us |  5.771 us |  5.398 us |
|      GetDoubleEma |   174.90 us |  1.904 us |  1.781 us |
|            GetEma |    96.72 us |  1.919 us |  1.701 us |
|            GetFcb |   418.82 us |  4.011 us |  3.752 us |
|        GetFractal |   111.30 us |  2.195 us |  2.855 us |
|     GetHeikinAshi |   172.42 us |  3.409 us |  3.925 us |
|            GetHma | 1,195.87 us | 10.118 us |  9.464 us |
|       GetIchimoku | 1,050.18 us | 13.228 us | 12.373 us |
|           GetKama |   318.65 us |  1.913 us |  1.696 us |
|        GetKeltner |   443.27 us |  5.761 us |  4.811 us |
|           GetMacd |   213.84 us |  2.355 us |  2.087 us |
|    GetMaEnvelopes |   142.76 us |  0.997 us |  0.884 us |
|           GetMama |   283.77 us |  4.557 us |  4.263 us |
|            GetMfi |   423.32 us |  3.052 us |  2.855 us |
|            GetObv |    57.61 us |  0.630 us |  0.492 us |
|     GetObvWithSma |   125.99 us |  1.091 us |  1.021 us |
|   GetParabolicSar |    93.09 us |  0.490 us |  0.409 us |
|    GetPivotPoints |    92.00 us |  1.179 us |  1.103 us |
|            GetPmo |   248.81 us |  2.457 us |  2.298 us |
|            GetPrs |   100.52 us |  0.241 us |  0.201 us |
|     GetPrsWithSma |   187.76 us |  2.682 us |  2.378 us |
|            GetPvo |   310.45 us |  2.365 us |  1.975 us |
|            GetRoc |    78.31 us |  0.281 us |  0.263 us |
|     GetRocWithSma |   338.07 us |  3.854 us |  3.605 us |
|            GetRsi |   298.01 us |  3.547 us |  3.318 us |
|          GetSlope |   924.09 us |  3.082 us |  2.574 us |
|            GetSma |    99.03 us |  0.518 us |  0.433 us |
|    GetSmaExtended |   903.12 us |  3.819 us |  3.572 us |
|         GetStdDev |   269.90 us |  1.871 us |  1.750 us |
|     GetStarcBands |   399.90 us |  2.413 us |  2.139 us |
|  GetStdDevWithSma |   358.36 us |  2.217 us |  2.074 us |
|          GetStoch |   387.38 us |  3.090 us |  2.890 us |
|       GetStochRsi |   640.82 us |  2.579 us |  2.153 us |
|     GetSuperTrend |   296.03 us |  2.525 us |  2.361 us |
|      GetTripleEma |   249.43 us |  0.830 us |  0.776 us |
|           GetTrix |   297.16 us |  0.794 us |  0.663 us |
|    GetTrixWithSma |   350.76 us |  3.173 us |  2.968 us |
|            GetTsi |   351.09 us |  6.821 us |  9.337 us |
|             GetT3 |   438.32 us |  2.098 us |  1.962 us |
|     GetUlcerIndex | 1,449.60 us |  9.323 us |  8.721 us |
|       GetUltimate |   517.06 us |  2.548 us |  2.384 us |
|         GetVolSma |   101.60 us |  0.733 us |  0.686 us |
|         GetVortex |   262.25 us |  2.850 us |  2.666 us |
|           GetVwap |    90.70 us |  0.322 us |  0.301 us |
|      GetWilliamsR |   279.28 us |  3.271 us |  3.060 us |
|            GetWma |   624.93 us |  7.734 us |  7.234 us |
|         GetZigZag |   124.47 us |  0.387 us |  0.362 us |

// * Hints *
Outliers
  MarkIndicators.GetAdl: Default            -> 1 outlier  was  removed (155.88 us)
  MarkIndicators.GetAdlWithSma: Default     -> 3 outliers were removed (347.69 us..359.94 us)
  MarkIndicators.GetAdx: Default            -> 2 outliers were removed (692.68 us, 693.46 us)
  MarkIndicators.GetAwesome: Default        -> 2 outliers were removed, 4 outliers were detected (317.81 us, 317.81 us, 322.47 us, 324.24 us)
  MarkIndicators.GetBollingerBands: Default -> 2 outliers were removed (474.53 us, 526.07 us)
  MarkIndicators.GetBop: Default            -> 2 outliers were removed (316.22 us, 322.09 us)
  MarkIndicators.GetCci: Default            -> 3 outliers were removed (771.20 us..773.88 us)
  MarkIndicators.GetChandelier: Default     -> 1 outlier  was  removed (373.58 us)
  MarkIndicators.GetChop: Default           -> 3 outliers were removed (307.36 us..314.39 us)
  MarkIndicators.GetCmf: Default            -> 1 outlier  was  removed (730.76 us)
  MarkIndicators.GetConnorsRsi: Default     -> 2 outliers were removed (1.20 ms, 1.21 ms)
  MarkIndicators.GetCorrelation: Default    -> 1 outlier  was  removed (991.50 us)
  MarkIndicators.GetEma: Default            -> 1 outlier  was  removed (123.18 us)
  MarkIndicators.GetHeikinAshi: Default     -> 1 outlier  was  removed (182.78 us)
  MarkIndicators.GetKama: Default           -> 1 outlier  was  removed (386.45 us)
  MarkIndicators.GetKeltner: Default        -> 2 outliers were removed (481.20 us, 554.51 us)
  MarkIndicators.GetMacd: Default           -> 1 outlier  was  removed (224.15 us)
  MarkIndicators.GetMaEnvelopes: Default    -> 1 outlier  was  removed (145.93 us)
  MarkIndicators.GetObv: Default            -> 3 outliers were removed (60.20 us..65.67 us)
  MarkIndicators.GetParabolicSar: Default   -> 2 outliers were removed (94.30 us, 98.02 us)
  MarkIndicators.GetPrs: Default            -> 2 outliers were removed (101.24 us, 102.53 us)
  MarkIndicators.GetPrsWithSma: Default     -> 1 outlier  was  removed (224.89 us)
  MarkIndicators.GetPvo: Default            -> 2 outliers were removed (315.85 us, 318.81 us)
  MarkIndicators.GetSlope: Default          -> 2 outliers were removed (938.33 us, 942.56 us)
  MarkIndicators.GetSma: Default            -> 2 outliers were removed (100.86 us, 100.94 us)
  MarkIndicators.GetStarcBands: Default     -> 1 outlier  was  removed (406.91 us)
  MarkIndicators.GetStochRsi: Default       -> 2 outliers were removed (652.70 us, 654.12 us)
  MarkIndicators.GetTrix: Default           -> 2 outliers were removed (299.45 us, 299.99 us)
  MarkIndicators.GetTsi: Default            -> 1 outlier  was  removed (379.48 us)
```

**Comment by tanjera** [comment]
> I think the acronym CHOP is fine, descriptive enough. From my quick scan, the code looks almost flawless, excellent work. I’ll do a full check this weekend.

Thank you!!

**Review by DaveSkender — APPROVED** [review]
:star::star::star::star::star:
Excellent work, five stars.

**Comment by tanjera** [comment]
> ⭐⭐⭐⭐⭐
> Excellent work, five stars.

Awesome, thank you! Glad to help!

I'll reach out when I'm up for another indicator or two. Might be a week or two until I have time.

**Pull request merged**
