### PR TITLE
refactor: test data

### PR DESCRIPTION
**Pull request by DaveSkender**
## Description

Converting tests from a sampling approach to a whole series evaluation using data files produced from manual calculations.
This can be rigged to simplify testing to some degree; albeit, at the expense of having lots of slower data files to import.

To do:

- [x] decide on how many of these to convert now, or opportunistically later
- [x] Lowercase `tests` folders consistency

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [x] I have added or run the performance tests that depict optimal execution times
- [x] New and existing unit tests pass locally and in the build (below) with my changes

## Acknowledgements

- [x] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [x] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by fuadbagus** [comment]
@DaveSkender Let me know if there is anything in particular you want me to have a look at. I'm going through the test-files branch locally to get my head around it.

**Comment by DaveSkender** [comment]
> Let me know if there is anything in particular you want me to have a look at. I'm going through the test-files branch locally to get my head around it.

@foudbagus I'll probably finish this PR later tonight and merge it; however, it can give you a sense of what I'm thinking and how we've been doing unit tests.  The basic approach has been to do the manual calculations in Excel, then test against sampled data from it.  @97nitt has been doing full series tests in our sister Java project and I thought it would be good to see if that works here too; essentially, we test every value in the indicator results, not just sampled data.

**Comment by DaveSkender** [comment]
I'm not 100% sure I love the approach I've implemented here, so if you have suggestions, feel free to review or comment.

**Comment by fuadbagus** [comment]
> 
> 
> I'm not 100% sure I love the approach I've implemented here, so if you have suggestions, feel free to review or comment.

@DaveSkender I'm looking at Dpo.Test as an example and it looks good. Clear Arrange, Act & Assert. As i read it, the intent it to read the calculated data and ensure that it matches the algo being tested

**Comment by fuadbagus** [comment]
> 
> 
> > I'm not 100% sure I love the approach I've implemented here, so if you have suggestions, feel free to review or comment.
> 
> @DaveSkender I'm looking at Dpo.Test as an example and it looks good. Clear Arrange, Act & Assert. As i read it, the intent it to read the calculated data and ensure that it matches the algo being tested

@DaveSkender Was wondering if there is some provider class that loads the data ?

**Comment by DaveSkender** [comment]
> is some provider class that loads the data?

I did not define one, but that's something we could do if it makes it cleaner and work better

**Comment by fuadbagus** [comment]
> 
> 
> > is some provider class that loads the data?
> 
> I did not define one, but that's something we could do if it makes it cleaner and work better

I think it might help from a consistency point of view on how data is read. I can help with improving how it works too.

**Review by fuadbagus — DISMISSED** [review]

**Comment by fuadbagus** [comment]
@DaveSkender Is the build failing due to the data path of test ?

**Review by fuadbagus — APPROVED** [review]

**Comment by DaveSkender** [comment]
> Is the build failing due to the data path of test?

Yes, it's making me crazy.  I think I fixed it though.  It only shows up when running the automated tests on the build server, so I had to keep pushing with a trial and error approach.  Ugh!

**Comment by DaveSkender** [comment]
@fuadbagus I've merged this to `main`.  Here's some tips on how to update your fork: #503 
If you want to make a new PR with your thoughts on how to make this better for my sample DPO case, please do.

**Comment by fuadbagus** [comment]
> 
> 
> @fuadbagus I've merged this to `main`. Here's some tips on how to update your fork: #503
> If you want to make a new PR with your thoughts on how to make this better for my sample DPO case, please do.

@DaveSkender Thank you. Will have a look

**Pull request merged**
