### PR TITLE
use any OHLCV part for SMA/EMA

### PR DESCRIPTION
**Pull request by DaveSkender**
## Description

Allows users to specify which part of the candle to use in SMA and EMA.
Implements #506

## Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [x] I have added or run the performance tests that depict optimal execution times
- [x] New and existing unit tests pass locally and in the build (below) with my changes

## Acknowledgements

- [x] I have read and understand [the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0)
- [x] I agree to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

### CODE REVIEW

**Comment by DaveSkender** [comment]
@bitwizardry these changes may be hard to read due to related refactoring; however, feel free to comment if you have any.

**Comment by bitwizardry** [comment]
Despite the fact that I'm a complete github noob, all approved to me! I'm really needing to make a course about it. :D

I imagined the enum like this, making it more readable:

`
        public enum CandlePart {
            Open,
            High,
            Low,
            Close,
            Volume
        }
`

But it's ok the way you did it!

**Comment by DaveSkender** [comment]
> I imagined the enum like this, making it more readable:
> `public enum CandlePart { Open, High, Low, Close, Volume }`
> But it's ok the way you did it!

Yeah, that's just cosmetic.  My enum file has others that are quite large collections that don't fit horizontally, so I'm just sticking with a convention.

**Comment by bitwizardry** [comment]
> Or are you referring to fully spelled out names?

Yes, just the enum members names.

**Comment by bitwizardry** [comment]
> If you were referring to spelled out, I think I agree with that. My prior internal use of single letters was okay for internal, but not great for public use.

 When I pasted the enum in response, it pasted vertically, (I also prefer the horizontal convention) I was talking about just about the members names. All right now!

**Comment by DaveSkender** [comment]
This will be available in the next release

**Pull request merged**
