### PR TITLE
add S3+R3 to Standard Pivot Points

### PR DESCRIPTION
**Pull request by myalgomate**
### Description

Adds S3+R3 to Standard Pivot Points
See #668

### Checklist

- [ ] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [ ] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DaveSkender** [comment]
This is the one to leave open, you should close the other one.  You can continue to add commits to that branch and they’ll be reflected here.

**Comment by DaveSkender** [comment]
I'm going to update S3 and R3 according to [Wikipedia](https://en.m.wikipedia.org/wiki/Pivot_point_(technical_analysis)):

```csharp
R3 = H + 2×(P − L) = R1 + (H − L)
S3 = L − 2×(H − P) = S1 − (H − L)
```

**Comment by DaveSkender** [comment]
@myalgomate do a review on this change; then I'll merge it.

**Comment by myalgomate** [comment]
Hi Dave,
The value gets differ for S3 and R3.

Better if we separate the new type with the name ChartIQ and follow the below calculations.
ChartIQ is an charting engine and its calculation is as below : 

<html>
<body>
<p style="font-family: Inter, sans-serif; font-size: 16px; font-weight: 400; line-height: 1.7; margin-left: auto; margin-right: auto; margin-bottom: 20px; -webkit-font-smoothing: antialiased; text-align: left; color: rgb(68, 68, 68); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pivot Points formula are calculated as follows on Kite for ChartIQ:</p>

KITE(ChartIQ)
--
Pivot point = (H + L + C) / 3
First support level (S1) = (2 * P) – H
Second support level (S2) = P – (H – L)
Third support level (S3) = P – 2*(H-L)
First resistance level (R1) = (2 * P) – L
Second resistance level (R2) = P + (H – L)
Third resistance level (R3) = P + 2*(H – L)

<p style="font-family: Inter, sans-serif; font-size: 16px; font-weight: 400; line-height: 1.7; margin-left: auto; margin-right: auto; margin-bottom: 20px; -webkit-font-smoothing: antialiased; text-align: left; color: rgb(68, 68, 68); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Please check<span> </span><a href="https://tradingqna.com/t/why-do-pivot-points-differ-on-kite-and-pi-how-is-this-calculated/15780/3" rel="noopener noreferrer" style="background-color: transparent; text-decoration: none; color: rgb(56, 126, 209);">this post</a><span> </span>on TradingQ&amp;A for a detailed explanation.</p>
</body>
</html>

**Comment by myalgomate** [comment]
you can push that changes in standard as Wikipedia and also add the ChartIQ type of Pivot

**Comment by DaveSkender** [comment]
Yah, these appear to be an entirely flavor, but do like the reputation and authenticity of the references in Wikipedia for extending Standard.

That blog sorta shows that there’s a lot of confusion around those other custom types.  I’m sure there are quite a few variants out there we’ve not covered, but I do want to only include ones from reputable authors.

**Comment by myalgomate** [comment]
Yeah, i understand the thing u suggested to rely on a reputed reference.
In India, all the brokers are integrated with the ChartIQ Charting Engine only. 

If possible please add it to the separate type so to avoid our standard Pivot confusion as well.

Atleast this will help all the ChartIQ platform users.

**Comment by DaveSkender** [comment]
Yes, best to keep separate.  To consider ChartIQ though, I’d like to first find out if their formula has a reputable author or if they simple wrote some random equations that looked nice.  It is possible, and I’ve seen this in other popular charting platforms, that they simply made a horrible mistake!  😄

**Pull request merged**
