### PR TITLE
Cci calculation error fixed.

### PR DESCRIPTION
**Pull request by SnnK**
Compared and verified on TradingView (BINANCE:BTCUSDT 4h)

### CODE REVIEW

**Comment by DaveSkender** [comment]
Can you describe the original error?  Also, please do not use TradingView as a benchmark or source of accuracy.  Most of their indicators are user provided and untested, see #318 as an example.

**Comment by DaveSkender** [comment]
From what I can tell from your code, all you’ve done is replace True Price (correct formula) with close price (incorrect formula).

**Comment by SnnK** [comment]
Hi @DaveSkender 

First of all thank you for this great repository.

I checked again.

An incorrect formula misled me. When it matched the TradingView results with my results, I didn't think much about it. Sorry.

**Comment by DaveSkender** [comment]
Not a problem and thank you for your feedback.  Being able to periodically double-check our formulas is a good thing.  There's a lot of bad information out there and part of my job is to sift through it and ensure that we have the most reliable library as possible.

**Pull request closed without merging**
