### PR TITLE
add 'Visualize BackTest Result'

### PR DESCRIPTION
**Pull request by tiger2014**
### Description

Let the backtest result be visualized with simple method

### CODE REVIEW

**Comment by tiger2014** [comment]
This is very a simple sample. Hope someone knowing more about the frontend can add a pane for indicators (i.e. MACD, RSI) on the chart. Thanks!

**Comment by DaveSkender** [comment]
The only place I’d consid

**Comment by DaveSkender** [comment]
The only place I’d consider putting something like this is in the example project.  I’m not keen on putting front-end rendering pieces here.  It might make a good, but separate, add-on package as part of #484

**Review by DaveSkender — CHANGES_REQUESTED** [review]
This can’t be part of the core library since it’s out of scope.  See notes above.

**Comment by tiger2014** [comment]
I see

**Comment by DaveSkender** [comment]
Another option here is to just make a standalone example and upload it to your original "show discussion" here: #1005

**Comment by DaveSkender** [comment]
Transferred to discussion

**Pull request closed without merging**
