### PR TITLE
add OHLC4

### PR DESCRIPTION
**Pull request by tiger2014**
add OHLC4 in Quote

### CODE REVIEW

**Comment by DaveSkender** [comment]
I have some guidance on how you can [create your own custom quote class](https://daveskender.github.io/Stock.Indicators/guide/#using-custom-quote-classes).
I have no use for this modification in [the package](https://www.nuget.org/packages/Skender.Stock.Indicators) itself.

**Comment by DaveSkender** [comment]
By the way, I'm probably reverting the nullable Quote mods because they have an adverse impact on performance.  Those nullable Quote changes were never released.  I'd recommend using the [released library package](https://www.nuget.org/packages/Skender.Stock.Indicators) instead of the raw source code; unless you're contributing to the library, of course.

**Comment by DaveSkender** [comment]
If your goal is to simply have and use OHLC4, just wait a bit for me to catch up.  I'm working towards some new features that will allow users to do something like this:

```csharp
quotes
  .Use(CandlePart.Close)
  .GetRsi(14);
```

**Comment by tiger2014** [comment]
Thank you, DaveSkender.

**Pull request closed without merging**
