### PR TITLE
add Demand Index

### LINKED ISSUE #701: add James Sibbet Demand Index

### PR DESCRIPTION
**Pull request by ooples**
### Description

adds James Sibbet Demand Index

Implements #701 

### Checklist

- [x] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [x] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or run the performance tests that depict optimal execution times
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DaveSkender** [comment]
In looking at source materials for Demand Index, I think the best formula to use is the one published by Thomas Aspray in both S&C Magazine and in John Murphy's book _Technical Analysis of the Financial Markets_.  It appears to be the formula you've used, so I think we're good at finding and confirming the best source.

I've attempted to do a manual calculation independently of looking at any code samples, including this one, so we have something to use as a basis for unit tests to confirm that this code works the same.  If they don't match, we'll have to review both the manual calculation and the code to see which one might have the error.

[DemandIndex.Calc.xlsx](https://github.com/DaveSkender/Stock.Indicators/files/8054321/DemandIndex.Calc.xlsx)

To complete this Pull Request, we'll still need to do these things (let me know if you want me to contribute to do any of these):

- [ ] add unit tests based on manual calculations and resolve any differences
- [ ] add indicator page to documentation site
- [ ] do a code review to fine-tune and refactor to optimize

From a quick scan of the code, before I get into an actual code review, here's a couple of initial things we may want to change:

- we can't really use an "any candlepart" approach here since this formula discretely uses Close, High, and Low
- lookback periods validation probably needs to be >= 1 due to the price change calculation
- need to run Code Cleanup to resolve a few minor formatting issues

**Comment by DaveSkender** [comment]
I keep seeing descriptions of Demand Index with things like:

> The Demand Index is a complex technical indicator developed by James Sibbet that utilizes over 20 columns of data to measure the ratio of buying pressure to selling pressure.

> The Demand Index calculations are too complex for this book (they require 21-columns of data)

I'm wondering if the Thomas Aspray interpretation is just an approximation of what it should be?  I wish I could find Sibbet's original 21 column version, in his own words.  It might explain some of the oddness that I'm seeing in my manual calculations.

**Comment by DaveSkender** [comment]
@ooples let me know if you're still working on this PR.  Closing due to staleness, but can reopen.  I still have this in the backlog with an indicator that I needed to do more research on this one.

**Comment by ooples** [comment]
@DaveSkender yep you told me to wait on this until you could do more research

**Pull request closed without merging**
