### PR TITLE
add Volume Profile

### LINKED ISSUE #358: Volume profile
Please add  Session Volume indicator [Volume Profile].

### PR DESCRIPTION
**Pull request by JGronholz**
@DaveSkender, the last commit has the three VP files. I'm still digesting the contributing guidelines...

Fixes #358

### CODE REVIEW

**Comment by DaveSkender** [comment]
@JGronholz, nice!  Thanks for helping.  Checkout #503 for some tips on managing your feature branches.  I suspect you'll need to rebase too.  Let me know if you have any questions.  You can ping me on Twitter if you want to swap info for private chat.

**Comment by DaveSkender** [comment]
Based on the amount of unrelated changes in this PR, it'd probably be easier for you to just save a copy of your work and fully delete and recreate your fork.  Also, to work with .NET 7, you'll need [Visual Studio 2022 preview edition](https://visualstudio.microsoft.com/vs/preview/).

**Comment by Cage-e** [comment]
looking forward to this merge :) 
Please let me know if I could be of any help to make the process faster.

**Comment by DaveSkender** [comment]
Oh, I thought you were just providing a suggestion.  I can't consider or take this change with all the other changes commingled in there and with the build failure.  You'd have to fix a bunch of stuff before I can proceed.

**Comment by DaveSkender** [comment]
Happy to take a look at a clean proposal if anyone wants to work on it.

**Comment by JGronholz** [comment]
I'll refork and include only the VP, theoretically, tonight.

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
